### PR TITLE
Update repo to allow a "platform" to opt for io or html websocket

### PR DESCRIPTION
**Pull request by kealjones-wk**
# Motivation
This repo currently only worked for io based projects meaning that it could not be used in a browser. This project also happens to be the main websocket connection method used by https://github.com/MichaelMarner/dart-redux-remote-devtools which we would like to take advantage of in the browser.

# Changes
- Reorganized the files to allow isolation of "dart:html" import
- Added "socket_platform"s that allow users to config which type of WebSocket they would like to use with the `Socket` class, defaults to `dart:io`'s WebSocket.
- Updated `Socket` class logic to use `globalSocketPlatform` in order to allow platform specific logic

This update allows users who would like to use the html based websocket to do so by simply adding:
```
import 'package:socketcluster_client/src/socket_platform.dart';
import 'package:socketcluster_client/src/socket_platform_http.dart';
```
and then in main adding:
```
 globalSocketPlatform = HttpSocketPlatform();
```

# Review
 - [ ] Testing on IO based platform to be sure that regressions don't exist for io based consumers (such as flutter)
 - [ ] Tests should be added to test `globalSocketPlatform` usage works as intended
 - [ ] Test for Socket Usage when in IO mode and HTML mode should be added

@pauldemarco I would love your feedback on this PR. If you have any issue with its approach please let me know and i would be happy to discuss. My teammates will also be reviewing to double check my work.

### CODE REVIEW

**Comment by kealjones-wk** [comment]
@pauldemarco Just curious if you've seen this yet. :)

**Comment by pauldemarco** [comment]
I’ll take a look, thanks!

**Comment by kealjones-wk** [comment]
no rush, i can always just fork this while this is in review, I was just hoping to contribute to everyone's benefit.

**Comment by pauldemarco** [comment]
This all looks good to me!

**Comment by pauldemarco** [comment]
Also, love that this is being used in the remote devtools, that's super cool!

**Comment by MichaelMarner** [comment]
Could this also be published to pub.dev? Latest version is still 0.0.3:

https://pub.dev/packages/socketcluster_client

I can then update the devtools dependency.

Thanks

**Pull request merged**
